[package]
name = "duckdb-jfr-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb-extension-framework = { git = "https://github.com/ocadaruma/duckdb-extension-framework.git", rev = "659460a" }
jfrs = { git = "https://github.com/ocadaruma/jfrs.git", rev = "e7000b6" }
rustc-hash = "1.1.0"

[lib]
name = "jfr_extension"
crate-type = ["cdylib"]

[profile.release]
debug = true
