[package]
name = "duckdb-jfr-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb-extension-framework = { git = "https://github.com/ocadaruma/duckdb-extension-framework.git", rev = "469abe7" }

[lib]
name = "jfr_extension"
crate-type = ["staticlib"]
