name: CI
on:
  push:
    branches: [master]
    tags:
      - '*'
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build extension for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: x86_64-linux
            os: ubuntu-latest
          - build: x86_64-macos
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - name: Test Rust
        run:
          cargo test
      - name: Test Java
        run:
          jdbc/gradlew test
      - name: Save JNI lib output
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: extension-build
          path: build/*
