name: CI
on:
  push:
    branches: [master]
    tags:
      - '*'
  pull_request:
    branches: [master]
jobs:
#  build:
#    name: Build extension for ${{ matrix.build }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        include:
#          - build: x86_64-linux
#            os: ubuntu-latest
#          - build: x86_64-macos
#            os: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Setup duckdb sources
#        run: |
#          make duckdb-sources
#      - name: Set up Rust for macos
#        if: ${{ startsWith(matrix.os, 'macos') }}
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          target: aarch64-apple-darwin
#      - name: Set up Rust for linux
#        if: ${{ !startsWith(matrix.os, 'macos') }}
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#      - name: Build extension
#        run: |
#          make loadable-extension
#      - name: Test Java
#        run: |
#          cd jdbc && ./gradlew test
#      - name: Save extension output
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: actions/upload-artifact@v2
#        with:
#          name: extension-build
#          path: build/*
#  test-rust:
#    name: Execute Rust test for ${{ matrix.build }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        include:
#          - build: x86_64-linux
#            os: ubuntu-latest
#          - build: x86_64-macos
#            os: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup duckdb sources
#        run: |
#          make duckdb-sources
#      - name: Set up Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#      - name: Test Rust
#        run: |
#          cargo test
  linux-release-64:
    # Builds binaries for linux_amd64_gcc4
    name: Linux (x64)
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: ./.github/actions/manylinux_2014_setup
      - name: Setup duckdb sources
        run: |
          make duckdb-sources
      - name: Set up Rust for linux
        if: ${{ !startsWith(matrix.os, 'macos') }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup dependencies
        run: |
          yum install -y llvm-toolset-7
      - name: Build extension
        run: |
          scl enable llvm-toolset-7 'make loadable-extension'
      - name: Test Java
        run: |
          cd jdbc && ./gradlew test
      - name: Save extension output
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: extension-build
          path: build/*
